DUlSine/urls.py
# -*- coding: utf-8 -*-
# vim: set ts=4

from django.conf.urls import patterns, url

urlpatterns = patterns('DUlSine.views.general',
    url(r'^$', 'index', name = 'index')
)

# Authentication
urlpatterns += patterns('django.contrib.auth.views',
    url(r'^accounts/login/$', 'login', name = 'accounts.login'),
    url(r'^accounts/logout/$', 'logout', {"template_name": "registration/logged_out_DUlSine.html"}, name = 'accounts.logout'),
)

urlpatterns += patterns('DUlSine.views.DPS',
    url(r'^(?P<structure>\d+)/DPS/$', 'index', name = 'dps.index'),
    url(r'^(?P<structure>\d+)/DPS/(?P<dim_id>\d+)/$', 'details', name = 'dps.dimensionnement.details'),
    url(r'^(?P<structure>\d+)/DPS/(?P<dim_id>\d+)/inscription/(?P<wish_num>\d+)/$', 'inscription', name = 'dimensionnement.inscription'),

    # Creating a new DPS in  steps:
    # * information on the organizer and on the DPS
    #  * loop between 'modification' and 'verification'
    # * list of every days
    # * adding a new day
    # * looping between 'modification' and 'verification'
    url(r'^DPS/demande/$', 'demande', name = 'dps.demande'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/$', 'demande_details', name = 'dps.demande.details'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/envoyer/$', 'demande_envoyer', name = 'dps.demande.envoyer'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/verification/$', 'demande_verification', name = 'dps.demande.verification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/modification/$', 'demande_modification', name = 'dps.demande.modification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/$', 'dimensionnement', name = 'dps.demande.dimensionnement'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/verification/$', 'dimensionnement_verification', name = 'dps.demande.dimensionnement.verification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/modification/$', 'dimensionnement_modification', name = 'dps.demande.dimensionnement.modification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/copy/$', 'dimensionnement_copy', name = 'dps.demande.dimensionnement.copy'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/delete/$', 'dimensionnement_delete', name = 'dps.demande.dimensionnement.delete'),

    # Managing DPS
    url(r'^(?P<structure>\d+)/admin/DPS/$', 'admin_index', name = 'dps.admin.index'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/$', 'admin_details', name = 'dps.admin.details'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/dimensionnement/(?P<dim_id>\d+)/$', 'admin_dimensionnement', name = 'dps.admin.dimensionnement.details'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/devis/$', 'devis', name = 'dps.admin.devis'),

    # Calendars in CalDav format
    # Two optional arguments given throug the url:
    # * avant : only return events that happend less than 'avant' days before
    # * apres : do not return events in more than 'apres' days
    url(r'^(?P<structure>\d+)/DPS/calendrier(?:/(?P<avant>\d+)(?:/(?P<apres>\d+))?)?/$', 'calendrier', name = 'dps.calendrier'),
)

urlpatterns += patterns('DUlSine.views.benevole',
    url(r'^(?P<structure>\d+)/benevoles/$', 'index', name = 'benevole.index'),
    url(r'^benevole/(?P<benevole_id>\d+)/$', 'details', name = 'benevole.details'),
    url(r'^benevole/(?P<benevole_id>\d+)/calendrier(?:/(?P<event_type>\w+))?(?:/(?P<avant>\d+)(?:/(?P<apres>\d+))?)?/$', 'calendrier', name = 'benevole.calendrier'),
    url(r'^benevole/inscription/$', 'inscription', name = 'benevole.inscription'),
    url(r'^benevole/inscription/confirmation/$', 'inscription_confirmation', name = 'benevole.inscription.confirmation'),
    url(r'^benevole/moncompte/$', 'moncompte', name = 'benevole.moncompte'),
)

DUlSine/models/DPS.py
# -*- coding: utf-8 -*-
# vim: set ts=4

import binascii
from decimal import Decimal
import math
import os

from django.db import models
from django.db.models import Q

from structure import Structure
from organisateur import Organisateur
from benevole import Benevole

from dulsine_commons import *


def random_hash():
    """ Create a random string of size 15 """
    return binascii.b2a_hex(os.urandom(15))


class DPS(models.Model):
    class Meta:
        app_label = 'DUlSine'
        verbose_name_plural = 'DPS'

    hash_id = models.CharField(unique = True, max_length = 30, default = random_hash)
    structure = models.ForeignKey(Structure, null = True, blank = True)

    organisateur = models.ForeignKey(Organisateur)
    intitule = models.CharField(max_length = 200)
    objet = models.CharField(max_length = 200)

    lieu = models.CharField(max_length = 400)
    circuit = models.CharField(max_length = 1, choices = CIRCUITS, default = CIRCUITS[0][0])
    superficie = models.IntegerField()
    distance = models.IntegerField()
    risques = models.CharField(max_length = 200)

    adresse_rdv = models.CharField(max_length = 500)
    contact_sur_place_nom = models.CharField(max_length = 200)
    contact_sur_place_prenom = models.CharField(max_length = 200)
    contact_sur_place_civilite = models.CharField(max_length = 4, choices = CIVILITES, default = CIVILITES[0][0])
    contact_sur_place_telephone = models.CharField(max_length = 20)

    prix = models.IntegerField(default = 0)
    remarques = models.CharField(max_length = 500, blank = True)

    def __unicode__(self):
        return self.intitule


RISQUES_P2 = (
    (Decimal("0.25"), 'Public Assis : spectacle, cérémonie culturelle, réunion publique'),
    (Decimal("0.3"), 'Public debout : cérémonie culturelle, réunion publique,restauration, exposition, foire, salon, comice agricole, ..'),
    (Decimal("0.35"), 'Public debout : spectacle avec public statique, fête foraine, rendez-vous sportif avec protection du public par rapport à l’évènement, ...'),
    (Decimal("0.4"), 'Public debout : spectacle avec public dynamique, danse, féria, fête votive, carnaval, spectacle de rue, évènement se déroulant sur plusieurs jours avec présence permanente du public')
)

RISQUES_E1 = (
    (Decimal("0.25"), 'Permanente (bâtiment, salle en dur,..) voies publics avec accès dégagés'),
    (Decimal("0.3"), 'Non permanente (gradins, tribunes, chapiteaux,..) espace naturels ≤ 2 hectares, brancardage 150m <longueur ≤300m Terrain en pente sur plus de 100 m'),
    (Decimal("0.35"), 'Espace naturels : 2 ha < surface ≤ 5 ha, brancardage 300m <longueur ≤600m, terrain en pente sur plus de 150m. Autres conditions d’accès difficile'),
    (Decimal("0.4"), 'Espaces naturels : surface > 5 hectares - Brancardage : longueur > 600m. Terrain en pente sur plus de 300m autres conditions d\'accès difficiles. Progression des secours rendue difficile par la présence du public')
)

RISQUES_E2 = (
    (Decimal("0.25"), '≤ 10 minutes'),
    (Decimal("0.3"), '> 10 minutes et ≤ 20 minutes'),
    (Decimal("0.35"), '> 20 minutes et ≤ 30 minutes'),
    (Decimal("0.4"), '> 30 minutes')
)


class Dimensionnement(models.Model):
    class Meta:
        app_label = 'DUlSine'
        ordering = ('debut', 'fin')

    DPS = models.ForeignKey(DPS)

    # If the name is not given, the DPS name is used instead
    nom = models.CharField(max_length = 200, blank = True)
    debut = models.DateTimeField()
    fin = models.DateTimeField()

    effectifs_acteurs = models.IntegerField(default = 0)
    age_acteurs = models.CharField(max_length = 50, blank = True)
    type_acteurs = models.CharField(max_length = 1, choices = TYPES_ACTEURS, blank = True)

    effectifs_public = models.IntegerField(default = 0)
    age_public = models.CharField(max_length = 50, blank = True)
    besoins_specifiques = models.CharField(max_length = 200, blank = True)

    medecin = models.CharField(max_length = 200, blank = True)
    infirmier = models.BooleanField(default = False)
    ambulance_prive = models.BooleanField(default = False)
    secours_public = models.CharField(max_length = 200, blank = True)
    secours_autre = models.CharField(max_length = 200, blank = True)

    centre_sdis = models.CharField(max_length = 200)
    hopital = models.CharField(max_length = 200)

    repas = models.BooleanField()

    P2 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_P2, default = RISQUES_P2[0][0])
    E1 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_E1, default = RISQUES_E1[0][0])
    E2 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_E2, default = RISQUES_E2[0][0])
    IS = models.IntegerField(null = True, blank = True)

    def __unicode__(self):
        if self.nom is not None:
            return u"%s : %s" % (self.DPS, self.nom)
        else:
            return u"%s : %s - %s" % (self.DPS, self.debut, self.fin)

    def shortName(self):
        if self.nom is not None:
            return self.nom
        else:
            return u"%s - %s" % (self.debut, self.fin)

    def getIndice(self):
        """
         Compute the risque indicator according to the law
          @return the indicator
        """
        return self.P2 + self.E1 + self.E2

    def calculRISPublic(self):
        return self.calculRIS(True)

    def calculRISActeur(self):
        return self.calculRIS(False)

    def calculRIS(self, public):
        """
         Compute the RIS (number of first aiders) according to the given informations
          @param public: True if the DPS is targetting the public. False for the actors.
          @return the RIS
        """
        indice = self.P2 + self.E1 + self.E2
        P = 0
        if(public):
            P = self.effectifs_public
        else:
            P = self.effectifs_acteurs

        if(P > 100000):
            P = 100000 + (P - 100000) / 2

        return indice * P / 1000

    def calculISPublic(self):
        return self.calculIS(True)

    def calculISActeur(self):
        return self.calculIS(False)

    def calculIS(self, public):
        """
         Compute the minimal number of first aiders
          @param public: True if the DPS is targetting the public. False for the actors.
          @return the minimal number of first aiders
        """
        ris = self.calculRIS(public)
        if(ris <= 0.25):
            num_is = 0
        elif(ris <= 1.125):
            num_is = 2
            # A PAPS is not enough when protecting actors and if the public
            # helps took more than 30 minutes to come (E2 = 0.40)
            if(public is False or self.E2 == 0.40):
                num_is = 4
        elif(ris <= 4):
            num_is = 4
        else:
            num_is = math.ceil(ris)
            # Round to the nearest odd number (upper bound)
            if(num_is % 2 == 1):
                num_is += 1

        return num_is

    # Compute the required number of the given person
    def nombreISMax(self, formation):
        if(self.IS is None):
            return 0

        if(formation == DIPLOME_CI):
            return (self.IS - self.IS % 4) / 4
        elif(formation == DIPLOME_PSE2):
            return (self.IS - self.IS % 4) / 2 + (self.IS % 4) / 2
        elif(formation == DIPLOME_PSE1):
            return (self.IS - self.IS % 4) / 4 + (self.IS % 4) / 2
        elif(formation == DIPLOME_PSC1):
            return Team.objects.filter(dimensionnement = self, team_type = 1).count()
        else:
            assert(0)

    # Compute the current number of the given person
    def nombreIS(self, formation):
        return Inscription.objects.filter(team__dimensionnement = self, fonction = formation).count()

    # Compute the number of benevole marked as not available
    def nombreND(self):
        return Wish.objects.filter(dimensionnement = self, wish = WISH_ND).count()

    def nombreD(self):
        return Wish.objects.filter(dimensionnement = self).filter(~Q(wish = WISH_ND)).count()


from team import Team, Inscription, Wish

DUlSine/models/benevole.py
# -*- coding: utf-8 -*-
# vim: set ts=4

from django.contrib.auth.models import User
from django.db import models

from structure import Structure

from dulsine_commons import DIPLOME_CONDUCTEURS_LIST, DIPLOME_FORMATEURS_LIST, DIPLOME_SECOURS_LIST


class Benevole(models.Model):
    class Meta:
        app_label = 'DUlSine'
        ordering = ('user__last_name', 'user__first_name')

    def __unicode__(self):
        return u"%s (%s)" % (self.user.get_full_name(), self.structure.nom)

    user = models.OneToOneField(User)
    structure = models.ForeignKey(Structure, verbose_name='structure de ratachement')

    # TODO: use https://docs.djangoproject.com/en/dev/ref/contrib/localflavor/
    telephone = models.IntegerField('téléphone')
    adresse = models.CharField('adresse', max_length = 200)
    date_naissance = models.DateField('date de naissance')
    diplomes = models.CommaSeparatedIntegerField('diplômes', max_length = 200)

    def listDiplomes(self, lookup):
        diplomes = []
        for token in self.diplomes.split(','):
            token = int(token)
            if token in lookup:
                diplomes.append(lookup[token])
        return diplomes

    # Return the only diploma for 'Secours'
    def diplomesSecours(self):
        return self.listDiplomes(DIPLOME_SECOURS_LIST)

    # Return the list of diploma for 'Conducteurs'
    def diplomesConducteur(self):
        return self.listDiplomes(DIPLOME_CONDUCTEURS_LIST)

    # Return the list of diploma for 'Formateur'
    def diplomesFormateur(self):
        return self.listDiplomes(DIPLOME_FORMATEURS_LIST)

DUlSine/models/organisateur.py
# -*- coding: utf-8 -*-
# vim: set ts=4

from django.db import models

from dulsine_commons import CIVILITES


class Organisateur(models.Model):
    class Meta:
        app_label = 'DUlSine'

    nom = models.CharField(max_length = 200)
    adresse = models.CharField(max_length = 500)

    contact_nom = models.CharField(max_length = 200)
    contact_prenom = models.CharField(max_length = 200)
    contact_civilite = models.CharField(max_length = 4, choices = CIVILITES, default = CIVILITES[0][0])
    contact_fonction = models.CharField(max_length = 200)

    representant_nom = models.CharField(max_length = 200)
    representant_prenom = models.CharField(max_length = 200)
    representant_civilite = models.CharField(max_length = 4, choices = CIVILITES, default = CIVILITES[0][0])
    representant_fonction = models.CharField(max_length = 200)

    telephone = models.CharField(max_length = 20, blank = True)
    portable = models.CharField(max_length = 20, blank = True)
    fax = models.CharField(max_length = 20, blank = True)
    email = models.EmailField(max_length = 100)

    def __unicode__(self):
        return self.nom

    def contact(self):
        return u"%s %s %s" % (self.get_contact_civilite_display(), self.contact_nom, self.contact_prenom)

    def representantLegal(self):
        return u"%s %s %s" % (self.get_representant_civilite_display(), self.representant_nom, self.representant_prenom)

models/delegation.py
# -*- coding: utf-8 -*-
# vim: set ts=4
from django.db import models

class Delegation(models.Model):
    class Meta:
        app_label = 'DUlSine'

    numero = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length = 50)
    adresse = models.CharField(max_length = 500)

    def __unicode__(self):
        return self.nom

templates/dps/demande.html
{% extends 'auth.html' %}


{% block titre %}DUlSine - Demande de DPS{% endblock %}


{% block corps %}
<div class="page-header">
  <h1>Demande de DPS</h1>
</div>

<p>Pour faire la demande pour un poste de secours (DPS), veuillez remplir le formulaire suivant aussi précisément que possible.<p>

<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
  <h2>Informations sur l'organisateur :</h2>
  <div class="row">
    <div class="span6">
      <legend>Contact :</legend>
      <div class="control-group {% if form_orga.contact_civilite.errors %}error{% endif %}">
        <label class="control-label" for="contact_civilite">Civilité</label>
        <div class="controls">
          {{ form_orga.contact_civilite.errors }}
          {% for radio in form_orga.contact_civilite %}
          {{ radio }}
          {% endfor %}
          {% for error in form_orga.contact_civilite.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_orga.contact_nom.errors %}error{% endif %}">
        <label class="control-label" for="id_contact_nom">Nom</label>
        <div class="controls">
          {{form_orga.contact_nom }}
          {% for error in form_orga.contact_nom.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_orga.contact_prenom.errors %}error{% endif %}">
        <label class="control-label" for="id_contact_prenom">Prénom</label>
        <div class="controls">
          {{form_orga.contact_prenom }}
          {% for error in form_orga.contact_prenom.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_orga.contact_fonction.errors %}error{% endif %}">
        <label class="control-label" for="id_contact_fonction">Fonction</label>
        <div class="controls">
          {{form_orga.contact_fonction }}
          {% for error in form_orga.contact_fonction.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="span6">
      <legend>Représentant légal :</legend>
      <div class="control-group {% if form_orga.representant_civilite.errors %}error{% endif %}">
        <label class="control-label" for="representant_civilite">Civilité</label>
        <div class="controls">
          {% for radio in form_orga.representant_civilite %}
          {{ radio }}
          {% endfor %}
          {% for error in form_orga.representant_civilite.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_orga.representant_nom.errors %}error{% endif %}">
        <label class="control-label" for="id_representant_nom">Nom</label>
        <div class="controls">
          {{form_orga.representant_nom }}
          {% for error in form_orga.representant_nom.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_orga.representant_prenom.errors %}error{% endif %}">
        <label class="control-label" for="id_representant_prenom">Prénom</label>
        <div class="controls">
          {{form_orga.representant_prenom }}
          {% for error in form_orga.representant_prenom.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_orga.representant_fonction.errors %}error{% endif %}">
        <label class="control-label" for="id_representant_fonction">Fonction</label>
        <div class="controls">
          {{form_orga.representant_fonction }}
          {% for error in form_orga.representant_fonction.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <legend>Organisation :</legend>
      <div class="row">
        <div class="span6">
          <div class="control-group {% if form_orga.nom.errors %}error{% endif %}">
            <label class="control-label" for="id_nom">Nom</label>
            <div class="controls">
              {{ form_orga.nom }}
              {% for error in form_orga.nom.errors %}
              <span class="help-inline">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="control-group {% if form_orga.adresse.errors %}error{% endif %}">
            <label class="control-label" for="id_adresse">Adresse</label>
            <div class="controls">
              {{ form_orga.adresse }}
              {% for error in form_orga.adresse.errors %}
              <span class="help-inline">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="span6">
          <div class="control-group {% if form_orga.telephone.errors %}error{% endif %}">
            <label class="control-label" for="id_telephone">Téléphone</label>
            <div class="controls">
              {{ form_orga.telephone }}
              {% for error in form_orga.telephone.errors %}
              <span class="help-inline">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="control-group {% if form_orga.portable.errors %}error{% endif %}">
            <label class="control-label" for="id_portable">Portable</label>
            <div class="controls">
              {{ form_orga.portable }}
              {% for error in form_orga.portable.errors %}
              <span class="help-inline">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="control-group {% if form_orga.fax.errors %}error{% endif %}">
            <label class="control-label" for="id_fax">Fax</label>
            <div class="controls">
              {{ form_orga.fax }}
              {% for error in form_orga.fax.errors %}
              <span class="help-inline">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
          <div class="control-group {% if form_orga.email.errors %}error{% endif %}">
            <label class="control-label" for="id_email">Email</label>
            <div class="controls">
              {{ form_orga.email }}
              {% for error in form_orga.email.errors %}
              <span class="help-inline">{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <h2>Information sur la manifestation :</h2>
  <div class="row">
    <div class="span6">
      <legend>Informations générales</legend>
      <div class="control-group {% if form_dps.intitule.errors %}error{% endif %}">
        <label class="control-label" for="id_intitule">Intitulé</label>
        <div class="controls">
          {{ form_dps.intitule }}
          {% for error in form_dps.intitule.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.objet.errors %}error{% endif %}">
        <label class="control-label" for="id_object">Objet</label>
        <div class="controls">
          {{ form_dps.objet }}
          {% for error in form_dps.objet.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.adresse_rdv.errors %}error{% endif %}">
        <label class="control-label" for="id_adresse_rdv">Adresse de rendez-vous</label>
        <div class="controls">
          {{ form_dps.adresse_rdv }}
          {% for error in form_dps.adresse_rdv.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="span6">
      <legend>Contact sur place</legend>
      <div class="control-group {% if form_dps.contact_sur_place_civilite.errors %}error{% endif %}">
        <label class="control-label" for="contact_sur_place_civilite">Civilite</label>
        <div class="controls">
          {% for radio in form_dps.contact_sur_place_civilite %}
          {{ radio }}
          {% endfor %}
          {% for error in form_dps.contact_sur_place_civilite.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.contact_sur_place_nom.errors %}error{% endif %}">
        <label class="control-label" for="id_contact_sur_place_nom">Nom</label>
        <div class="controls">
          {{ form_dps.contact_sur_place_nom }}
          {% for error in form_dps.contact_sur_place_nom.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.contact_sur_place_prenom.errors %}error{% endif %}">
        <label class="control-label" for="id_contact_sur_place_prenom">Prénom</label>
        <div class="controls">
          {{ form_dps.contact_sur_place_prenom }}
          {% for error in form_dps.contact_sur_place_prenom.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.contact_sur_place_telephone.errors %}error{% endif %}">
        <label class="control-label" for="id_contact_sur_place_telephone">Téléphone</label>
        <div class="controls">
          {{ form_dps.contact_sur_place_telephone }}
          {% for error in form_dps.contact_sur_place_telephone.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <legend>Caractéristiques du lieu</legend>
      <div class="control-group {% if form_dps.lieu.errors %}error{% endif %}">
        <label class="control-label" for="id_lieu">Adresse</label>
        <div class="controls">
          {{ form_dps.lieu }}
          {% for error in form_dps.lieu.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.circuit.errors %}error{% endif %}">
        <label class="control-label" for="id_circuit">Circuit</label>
        <div class="controls">
          {{ form_dps.circuit }}
          {% for error in form_dps.circuit.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.distance.errors %}error{% endif %}">
        <label class="control-label" for="id_distance">Distance entre les deux points les plus éloingé du site</label>
        <div class="controls">
          <div class="input-append">
            {{ form_dps.distance }}<span class="add-on"> mètres</span>
          </div>
          {% for error in form_dps.distance.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.superficie.errors %}error{% endif %}">
        <label class="control-label" for="id_superficie">Superficie du site</label>
        <div class="controls">
          <div class="input-append">
            {{ form_dps.superficie }}<span class="add-on"> mètre carrés</span>
          </div>
          {% for error in form_dps.superficie.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form_dps.risques.errors %}error{% endif %}">
        <label class="control-label" for="id_risques">Risques</label>
        <div class="controls">
          {{ form_dps.risques }}
          {% for error in form_dps.risques.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <button type="submit" class="btn">{% if nouveau %}Envoyer la demande{% else %}Enregistrer{% endif %}</button>
</form>
{% endblock %}