DUlSine/urls.py
# -*- coding: utf-8 -*-
# vim: set ts=4

from django.conf.urls import patterns, url

urlpatterns = patterns('DUlSine.views.general',
    url(r'^$', 'index', name = 'index')
)

# Authentication
urlpatterns += patterns('django.contrib.auth.views',
    url(r'^accounts/login/$', 'login', name = 'accounts.login'),
    url(r'^accounts/logout/$', 'logout', {"template_name": "registration/logged_out_DUlSine.html"}, name = 'accounts.logout'),
)

urlpatterns += patterns('DUlSine.views.DPS',
    url(r'^(?P<structure>\d+)/DPS/$', 'index', name = 'dps.index'),
    url(r'^(?P<structure>\d+)/DPS/(?P<dim_id>\d+)/$', 'details', name = 'dps.dimensionnement.details'),
    url(r'^(?P<structure>\d+)/DPS/(?P<dim_id>\d+)/inscription/(?P<wish_num>\d+)/$', 'inscription', name = 'dimensionnement.inscription'),

    # Creating a new DPS in  steps:
    # * information on the organizer and on the DPS
    #  * loop between 'modification' and 'verification'
    # * list of every days
    # * adding a new day
    # * looping between 'modification' and 'verification'
    url(r'^DPS/demande/$', 'demande', name = 'dps.demande'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/$', 'demande_details', name = 'dps.demande.details'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/envoyer/$', 'demande_envoyer', name = 'dps.demande.envoyer'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/verification/$', 'demande_verification', name = 'dps.demande.verification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/modification/$', 'demande_modification', name = 'dps.demande.modification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/$', 'dimensionnement', name = 'dps.demande.dimensionnement'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/verification/$', 'dimensionnement_verification', name = 'dps.demande.dimensionnement.verification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/modification/$', 'dimensionnement_modification', name = 'dps.demande.dimensionnement.modification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/copy/$', 'dimensionnement_copy', name = 'dps.demande.dimensionnement.copy'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/delete/$', 'dimensionnement_delete', name = 'dps.demande.dimensionnement.delete'),

    # Managing DPS
    url(r'^(?P<structure>\d+)/admin/DPS/$', 'admin_index', name = 'dps.admin.index'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/$', 'admin_details', name = 'dps.admin.details'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/dimensionnement/(?P<dim_id>\d+)/$', 'admin_dimensionnement', name = 'dps.admin.dimensionnement.details'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/devis/$', 'devis', name = 'dps.admin.devis'),

    # Calendars in CalDav format
    # Two optional arguments given throug the url:
    # * avant : only return events that happend less than 'avant' days before
    # * apres : do not return events in more than 'apres' days
    url(r'^(?P<structure>\d+)/DPS/calendrier(?:/(?P<avant>\d+)(?:/(?P<apres>\d+))?)?/$', 'calendrier', name = 'dps.calendrier'),
)

urlpatterns += patterns('DUlSine.views.benevole',
    url(r'^(?P<structure>\d+)/benevoles/$', 'index', name = 'benevole.index'),
    url(r'^benevole/(?P<benevole_id>\d+)/$', 'details', name = 'benevole.details'),
    url(r'^benevole/(?P<benevole_id>\d+)/calendrier(?:/(?P<event_type>\w+))?(?:/(?P<avant>\d+)(?:/(?P<apres>\d+))?)?/$', 'calendrier', name = 'benevole.calendrier'),
    url(r'^benevole/inscription/$', 'inscription', name = 'benevole.inscription'),
    url(r'^benevole/inscription/confirmation/$', 'inscription_confirmation', name = 'benevole.inscription.confirmation'),
    url(r'^benevole/moncompte/$', 'moncompte', name = 'benevole.moncompte'),
)

DUlSine/models/DPS.py
# -*- coding: utf-8 -*-
# vim: set ts=4

import binascii
from decimal import Decimal
import math
import os

from django.db import models
from django.db.models import Q

from structure import Structure
from organisateur import Organisateur
from benevole import Benevole

from dulsine_commons import *


def random_hash():
    """ Create a random string of size 15 """
    return binascii.b2a_hex(os.urandom(15))


class DPS(models.Model):
    class Meta:
        app_label = 'DUlSine'
        verbose_name_plural = 'DPS'

    hash_id = models.CharField(unique = True, max_length = 30, default = random_hash)
    structure = models.ForeignKey(Structure, null = True, blank = True)

    organisateur = models.ForeignKey(Organisateur)
    intitule = models.CharField(max_length = 200)
    objet = models.CharField(max_length = 200)

    lieu = models.CharField(max_length = 400)
    circuit = models.CharField(max_length = 1, choices = CIRCUITS, default = CIRCUITS[0][0])
    superficie = models.IntegerField()
    distance = models.IntegerField()
    risques = models.CharField(max_length = 200)

    adresse_rdv = models.CharField(max_length = 500)
    contact_sur_place_nom = models.CharField(max_length = 200)
    contact_sur_place_prenom = models.CharField(max_length = 200)
    contact_sur_place_civilite = models.CharField(max_length = 4, choices = CIVILITES, default = CIVILITES[0][0])
    contact_sur_place_telephone = models.CharField(max_length = 20)

    prix = models.IntegerField(default = 0)
    remarques = models.CharField(max_length = 500, blank = True)

    def __unicode__(self):
        return self.intitule


RISQUES_P2 = (
    (Decimal("0.25"), 'Public Assis : spectacle, cérémonie culturelle, réunion publique'),
    (Decimal("0.3"), 'Public debout : cérémonie culturelle, réunion publique,restauration, exposition, foire, salon, comice agricole, ..'),
    (Decimal("0.35"), 'Public debout : spectacle avec public statique, fête foraine, rendez-vous sportif avec protection du public par rapport à l’évènement, ...'),
    (Decimal("0.4"), 'Public debout : spectacle avec public dynamique, danse, féria, fête votive, carnaval, spectacle de rue, évènement se déroulant sur plusieurs jours avec présence permanente du public')
)

RISQUES_E1 = (
    (Decimal("0.25"), 'Permanente (bâtiment, salle en dur,..) voies publics avec accès dégagés'),
    (Decimal("0.3"), 'Non permanente (gradins, tribunes, chapiteaux,..) espace naturels ≤ 2 hectares, brancardage 150m <longueur ≤300m Terrain en pente sur plus de 100 m'),
    (Decimal("0.35"), 'Espace naturels : 2 ha < surface ≤ 5 ha, brancardage 300m <longueur ≤600m, terrain en pente sur plus de 150m. Autres conditions d’accès difficile'),
    (Decimal("0.4"), 'Espaces naturels : surface > 5 hectares - Brancardage : longueur > 600m. Terrain en pente sur plus de 300m autres conditions d\'accès difficiles. Progression des secours rendue difficile par la présence du public')
)

RISQUES_E2 = (
    (Decimal("0.25"), '≤ 10 minutes'),
    (Decimal("0.3"), '> 10 minutes et ≤ 20 minutes'),
    (Decimal("0.35"), '> 20 minutes et ≤ 30 minutes'),
    (Decimal("0.4"), '> 30 minutes')
)


class Dimensionnement(models.Model):
    class Meta:
        app_label = 'DUlSine'
        ordering = ('debut', 'fin')

    DPS = models.ForeignKey(DPS)

    # If the name is not given, the DPS name is used instead
    nom = models.CharField(max_length = 200, blank = True)
    debut = models.DateTimeField()
    fin = models.DateTimeField()

    effectifs_acteurs = models.IntegerField(default = 0)
    age_acteurs = models.CharField(max_length = 50, blank = True)
    type_acteurs = models.CharField(max_length = 1, choices = TYPES_ACTEURS, blank = True)

    effectifs_public = models.IntegerField(default = 0)
    age_public = models.CharField(max_length = 50, blank = True)
    besoins_specifiques = models.CharField(max_length = 200, blank = True)

    medecin = models.CharField(max_length = 200, blank = True)
    infirmier = models.BooleanField(default = False)
    ambulance_prive = models.BooleanField(default = False)
    secours_public = models.CharField(max_length = 200, blank = True)
    secours_autre = models.CharField(max_length = 200, blank = True)

    centre_sdis = models.CharField(max_length = 200)
    hopital = models.CharField(max_length = 200)

    repas = models.BooleanField()

    P2 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_P2, default = RISQUES_P2[0][0])
    E1 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_E1, default = RISQUES_E1[0][0])
    E2 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_E2, default = RISQUES_E2[0][0])
    IS = models.IntegerField(null = True, blank = True)

    def __unicode__(self):
        if self.nom is not None:
            return u"%s : %s" % (self.DPS, self.nom)
        else:
            return u"%s : %s - %s" % (self.DPS, self.debut, self.fin)

    def shortName(self):
        if self.nom is not None:
            return self.nom
        else:
            return u"%s - %s" % (self.debut, self.fin)

    def getIndice(self):
        """
         Compute the risque indicator according to the law
          @return the indicator
        """
        return self.P2 + self.E1 + self.E2

    def calculRISPublic(self):
        return self.calculRIS(True)

    def calculRISActeur(self):
        return self.calculRIS(False)

    def calculRIS(self, public):
        """
         Compute the RIS (number of first aiders) according to the given informations
          @param public: True if the DPS is targetting the public. False for the actors.
          @return the RIS
        """
        indice = self.P2 + self.E1 + self.E2
        P = 0
        if(public):
            P = self.effectifs_public
        else:
            P = self.effectifs_acteurs

        if(P > 100000):
            P = 100000 + (P - 100000) / 2

        return indice * P / 1000

    def calculISPublic(self):
        return self.calculIS(True)

    def calculISActeur(self):
        return self.calculIS(False)

    def calculIS(self, public):
        """
         Compute the minimal number of first aiders
          @param public: True if the DPS is targetting the public. False for the actors.
          @return the minimal number of first aiders
        """
        ris = self.calculRIS(public)
        if(ris <= 0.25):
            num_is = 0
        elif(ris <= 1.125):
            num_is = 2
            # A PAPS is not enough when protecting actors and if the public
            # helps took more than 30 minutes to come (E2 = 0.40)
            if(public is False or self.E2 == 0.40):
                num_is = 4
        elif(ris <= 4):
            num_is = 4
        else:
            num_is = math.ceil(ris)
            # Round to the nearest odd number (upper bound)
            if(num_is % 2 == 1):
                num_is += 1

        return num_is

    # Compute the required number of the given person
    def nombreISMax(self, formation):
        if(self.IS is None):
            return 0

        if(formation == DIPLOME_CI):
            return (self.IS - self.IS % 4) / 4
        elif(formation == DIPLOME_PSE2):
            return (self.IS - self.IS % 4) / 2 + (self.IS % 4) / 2
        elif(formation == DIPLOME_PSE1):
            return (self.IS - self.IS % 4) / 4 + (self.IS % 4) / 2
        elif(formation == DIPLOME_PSC1):
            return Team.objects.filter(dimensionnement = self, team_type = 1).count()
        else:
            assert(0)

    # Compute the current number of the given person
    def nombreIS(self, formation):
        return Inscription.objects.filter(team__dimensionnement = self, fonction = formation).count()

    # Compute the number of benevole marked as not available
    def nombreND(self):
        return Wish.objects.filter(dimensionnement = self, wish = WISH_ND).count()

    def nombreD(self):
        return Wish.objects.filter(dimensionnement = self).filter(~Q(wish = WISH_ND)).count()


from team import Team, Inscription, Wish

DUlSine/templates/dps/admin/details.html
{% extends 'auth.html' %}

{% load dulsine_extras %}

{% block titre %}{{ structure }} - {{ dps }}{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="{% url 'index' %}">Accueil</a> <span class="divider">/</span></li>
  <li><a href="#">Admin</a> <span class="divider">/</span></li>
  <li><a href="{% url 'dps.admin.index' user.benevole.structure.numero %}">DPS</a> <span class="divider">/</span></li>
  <li class="active">{{ dps }}</li>
</ul>
{% endblock %}

{% block corps %}
<div class="page-header">
  <h1>{{ dps }}</h1>
</div>

<div class="row">
  <div class="span6">
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Organisateur</a></li>
        <li><a href="#tab2" data-toggle="tab">Coordonnées</a></li>
        <li><a href="#tab3" data-toggle="tab">Manifestation</a></li>
        <li><a href="#tab4" data-toggle="tab">Lieu</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <dl class="dl-horizontal">
            <dt>Nom</dt>
            <dd>{{ dps.organisateur.nom }}</dd>
            <dt>Adresse<dt>
            <dd>{{ dps.organisateur.adresse }}</dd>
            <dt>Représentant légale</dt>
            <dd>{{ dps.organisateur.representant_civilite }} {{ dps.organisateur.representant_nom }} {{ dps.organisateur.representant_prenom }}, {{ dps.organisateur.representant_fonction }}</dd>
          </dl>
        </div>
        <div class="tab-pane" id="tab2">
          <dl class="dl-horizontal">
            <dt>Contact</dt>
            <dd>{{ dps.organisateur.contact_civilite }} {{ dps.organisateur.contact_nom }} {{ dps.organisateur.contact_prenom }}, {{ dps.organisateur.contact_fonction }}</dd>
            {% if dps.organisateur.telephone %}
            <dt>Téléphone</dt>
            <dd><a href="tel:{{ dps.organisateur.telephone }}">{{ dps.organisateur.telephone }}</a></dd>
            {% endif %}
            {% if dps.organisateur.portable %}
            <dt>Portable</dt>
            <dd><a href="tel:{{ dps.organisateur.portable }}">{{ dps.organisateur.portable }}</a></dd>
            {% endif %}
            {% if dps.organisateur.fax %}
            <dt>Fax</dt>
            <dd>{{ dps.organisateur.fax }}</dd>
            {% endif %}
            <dt>email</dt>
            <dd><a href="mailto:{{ dps.organisateur.email }}">{{ dps.organisateur.email }}</a></dd>
            <dt>Contact sur place</dt>
            <dd>{{ dps.contact_sur_place_civilite }} {{ dps.contact_sur_place_nom }} {{ dps.contact_sur_place_prenom }} (<a href="tel:{{ dps.contact_sur_place_telephone }}">{{ dps.contact_sur_place_telephone }}</a>)</dd>
          </dl>
        </div>
        <div class="tab-pane" id="tab3">
          <dl class="dl-horizontal">
            <dt>Intitulé</dt>
            <dd>{{ dps.intitule }}</dd>
            <dt>Objet</dt>
            <dd>{{ dps.objet }}</dd>
            <dt>Risques</dt>
            <dd>{{ dps.risques }}</dd>
          </dl>
        </div>
        <div class="tab-pane" id="tab4">
          <dl class="dl-horizontal">
            <dt>Lieu</dt>
            <dd>{{ dps.lieu }}</dd>
            <dt>RdV</dt>
            <dd>{{ dps.adresse_rdv }}</dd>
            {% if dps.duperficie %}
            <dt>Superficie</dt>
            <dd>{{ dps.superficie }} m²</dd>
            {% endif %}
            {% if dps.distance %}
            <dt>Distance</dt>
            <dd>{{ dps.distance }} m</dd>
            {% endif %}
            <dt>Circuit</dt>
            <dd>{{ dps.get_circuit_display }}</dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
  <div class="span6">
    <dl class="dl-horizontal">
      <dt>Status</dt>
      <dd>{{ dps.status|default:"???" }}</dd>
      <dt>Devis</dt>
      <dd><a href="{% url 'dps.admin.devis' dps.structure.pk dps.id %}">Generer</a></dd>
      <dt>Convention<dt>
      <dd><a href="#">Generer</a></dd>
    </dl>
  </div>
</div>

<h2>Dimensionnements</h2>
<div class="row">
  {% regroup all_dim by debut|date:"F o" as all_dim_by_months %}
  {% for month in all_dim_by_months %}
  <div class="span12">
    <h4>{{ month.grouper|capfirst }}</h4>
    <table class="table table-striped">
    <thead>
    <tr>
     <th width="10%">Date</th>
     <th width="10%">Horaire</th>
     <th width="25%">DPS</th>
     <th width="20%">Dimensionnement</th>
     <th width="10%">Status</th>
     <th width="5%">D/ND</th>
     <th width="5%">CI</th>
     <th width="5%">PSE2</th>
     <th width="5%">PSE1</th>
     <th width="5%">PSC1</th>
    </tr>
    </thead>

    {% for dim in month.list %}
    <tr>
      <td>{{ dim.debut|date:"D d"|capfirst }}</td>
      <td>{{ dim.debut|date:"H:i" }} - {{ dim.fin|date:"H:i" }}</td>
      <td>{{ dim.DPS.intitule }}</td>
      <td><a href="{% url 'dps.admin.dimensionnement.details' dim.DPS.structure.pk dim.DPS.id dim.id %}">{{ dim.shortName }}</a></td>
      <td>???</td>
      <td><span class="badge badge-default">{{ dim.nombreD }} / {{ dim.nombreND }}</span></td>
      <td>{% badge dim.id DIPLOME_CI %}</td>
      <td>{% badge dim.id DIPLOME_PSE2 %}</td>
      <td>{% badge dim.id DIPLOME_PSE1 %}</td>
      <td>{% badge dim.id DIPLOME_PSC1 %}</td>
    </tr>
    {% endfor %}
    </table>
  </div>
  {% endfor %}
</div>

{% endblock %}

DUlSine/templates/dps/admin/dimensionnement.html
{% extends 'auth.html' %}

{% load dulsine_extras %}

{% block titre %}{{ structure }} - Gestion des DPS{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="{% url 'index' %}">Accueil</a> <span class="divider">/</span></li>
  <li><a href="#">Admin</a> <span class="divider">/</span></li>
  <li><a href="{% url 'dps.admin.index' user.benevole.structure.numero %}">DPS</a> <span class="divider">/</span></li>
  <li><a href="{% url 'dps.admin.details' user.benevole.structure.numero dim.DPS.id %}">{{ dim.DPS }}</a> <span class="divider">/</span></li>
  <li class="active">{{ dim.shortName }}</li>
</ul>
{% endblock %}

{% block corps %}
<div class="page-header">
  <h1>{{ dim }} <small><a href="{% url 'dps.dimensionnement.details' dim.DPS.structure.numero dim.id %}">voir</a></small></h1>
</div>

<div class="row">
  <div class="span12">
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Dimensionnement</a></li>
        <li><a href="#tab2" data-toggle="tab">Risques</a></li>
        <li><a href="#tab3" data-toggle="tab">RIS</a></li>
        <li><a href="#tab4" data-toggle="tab">Secours</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <dl class="dl-horizontal">
            <dt>Intitulé</dt>
            <dd>{{ dim.nom }}
            <dt>Date</dt>
            {% if dim.debut|date:"d/m/y" == dim.fin|date:"d/m/y" %}
            <dd>Le {{ dim.debut|date:"l d/m/y" }} de {{ dim.debut|date:"H:i" }} à {{ dim.fin|date:"H:i" }}</dd>
            {% else %}
            <dd>Du {{ dim.debut|date:"l d/m/y" }} à {{ dim.debut|date:"H:i" }} au {{ dim.fin|date:"l d/m/y" }} à {{ dim.fin|date:"H:i" }}</dd>
            {% endif %}
            {% if dim.effectifs_public > 0 %}
            <dt>Public</dt>
            <dd>{{ dim.effectifs_public }} personnes de {{ dim.age_public }} (besoins specifiques : {{ dim.besoins_specifiques }})</dd>
            {% endif %}
            {% if dim.effectifs_acteurs > 0 %}
            <dt>Acteurs</dt>
            <dd>{{ dim.effectifs_acteurs }} personnes de {{ dim.age_acteurs }} ({{ dim.get_type_acteurs_display }})
            {% endif %}
          </dl>
        </div>
        <div class="tab-pane" id="tab2">
          <dl class="dl-horizontal">
            <dt>Comportement</dt>
            <dd>{{ dim.get_P2_display }}</dd>
            <dt>Structure</dt>
            <dd>{{ dim.get_E1_display }}</dd>
            <dt>Secours public</dt>
            <dd>{{ dim.get_E2_display }}</dd>
          </dl>
        </div>
        <div class="tab-pane" id="tab3">
          <dl class="dl-horizontal">
            <dt>P2+E1+E2</dt>
            <dd>{{ dim.P2 }} + {{ dim.E1 }} + {{ dim.E2 }} = {{ dim.getIndice }}</dd>
            {% if dim.effectifs_public %}
            <dt>IS public</dt>
            <dd>{{ dim.calculISPublic }} (RIS : {{ dim.calculRISPublic }})</dd>
            {% endif %}
            {% if dim.effectifs_acteurs %}
            <dt>IS acteur</dt>
            <dd>{{ dim.calculISActeur }} (RIS : {{ dim.calculRISActeur }})</dd>
            {% endif %}
            <dt>IS effectif</dt>
            <dd>{{ dim.IS }}</dd>
          </dl>
        </div>
        <div class="tab-pane" id="tab4">
          <dl class="dl-horizontal">
            <dt>Centre de secours</dt>
            <dd>{{ dim.centre_sdis }}</dd>
            <dt>Hopital</dt>
            <dd>{{ dim.hopital }}</dd>
            {% if dim.secours_public %}
            <dt>Secours public présent</dt>
            <dd>{{ dim.secours_public }}</dd>
            {% endif %}
            {% if dim.medecin %}
            <dt>Médecin</dt>
            <dd>{{ dim.medecin }}</dd>
            {% endif %}
            {% if dim.infirmier %}
            <dt>Présence d'un infirmier</dt>
            <dd>Oui</dd>
            {% endif %}
            {% if dim.ambulance_prive %}
            <dt>Ambulance privée</dt>
            <dd>Oui</dd>
            {% endif %}
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="span12">
    <h4 class="modal-header">Équipes</h4>
    {% for team in teams %}
    <p>{{ team.get_team_type_display }}</p>
    {% endfor %}
  </div>

  <div class="span12">
    {% if wishes %}
    <h4 class="modal-header">Personnes disponibles</h4>
    <table class="table table-striped">
    <thead>
      <tr>
        <th width="25%">Nom</th>
        <th width="25%">Prénom</th>
        <th width="15%">Souhait</th>
        <th width="15%">Date</th>
        <th width="10%"></th>
      <tr>
    </thead>
    {% for wish in wishes %}
      <tr>
        <td>{{ wish.benevole.user.last_name }}</td>
        <td>{{ wish.benevole.user.first_name }}</td>
        <td>{{ wish.get_wish_display }}</td>
        <td>{{ wish.date|date:"d/m/Y H:i" }}</td>
        <td><a href="#"><i class="icon-plus-sign"></i>Sélectionner</a></td>
      </tr>
    {% endfor %}
    </table>
    {% else %}
    <h4 class="modal-header">Aucunes disponibilités</h4>
    {% endif %}
  </div>

  <div class="span12">
    {% if not_available %}
    <h4 class="modal-header">Personnes indisponibles</h4>
    <table class="table table-striped">
    <thead>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Date</th>
    </thead>
    {% for na in not_available %}
    <tr>
      <td>{{ na.benevole.user.last_name }}</td>
      <td>{{ na.benevole.user.first_name }}</td>
      <td>{{ na.date|date:"d/m/Y H:i" }}</td>
    </tr>
    {% endfor %}
    </table>
    {% endif %}
  </div>
</div>
{% endblock %}

DUlSine/templates/dps/admin/index.html
{% extends 'auth.html' %}

{% load dulsine_extras %}

{% block titre %}{{ structure.nom }} - Gestion des DPS{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="{% url 'index' %}">Accueil</a> <span class="divider">/</span></li>
  <li><a href="#">Admin</a> <span class="divider">/</span></li>
  <li class="active">DPS</li>
</ul>
{% endblock %}

{% block corps %}
<div class="page-header">
  <h1>Liste des DPS <small>Administration</small></h1>
</div>

<div class="row">
{% regroup all_dim by debut|date:"F o" as all_dim_by_months %}
{% for month in all_dim_by_months %}

<div class="span12">
<h4>{{ month.grouper|capfirst }}</h4>
<table class="table table-striped">
<thead>
<tr>
  <th width="10%">Date</th>
  <th width="10%">Horaire</th>
  <th width="25%">DPS</th>
  <th width="20%">Dimensionnement</th>
  <th width="10%">Status</th>
  <th width="5%">D/ND</th>
  <th width="5%">CI</th>
  <th width="5%">PSE2</th>
  <th width="5%">PSE1</th>
  <th width="5%">PSC1</th>
</tr>
</thead>

{% for dim in month.list %}
<tr>
  <td>{{ dim.debut|date:"D d"|capfirst }}</td>
  <td>{{ dim.debut|date:"H:i" }} - {{ dim.fin|date:"H:i" }}</td>
  <td><a href="{% url 'dps.admin.details' dim.DPS.structure.pk dim.DPS.id %}">{{ dim.DPS.intitule }}</a></td>
  <td><a href="{% url 'dps.admin.dimensionnement.details' dim.DPS.structure.pk dim.DPS.id dim.id %}">{{ dim.shortName }}</a></td>
  <td>???</td>
  <td><span class="badge badge-default">{{ dim.nombreD }} / {{ dim.nombreND }}</span></td>
  <td>{% badge dim.id DIPLOME_CI %}</td>
  <td>{% badge dim.id DIPLOME_PSE2 %}</td>
  <td>{% badge dim.id DIPLOME_PSE1 %}</td>
  <td>{% badge dim.id DIPLOME_PSC1 %}</td>
</tr>
{% endfor %}
</table>
</div>

{% endfor %}
</div>

{% endblock %}