DUlSine/urls.py
# -*- coding: utf-8 -*-
# vim: set ts=4

from django.conf.urls import patterns, url

urlpatterns = patterns('DUlSine.views.general',
    url(r'^$', 'index', name = 'index')
)

# Authentication
urlpatterns += patterns('django.contrib.auth.views',
    url(r'^accounts/login/$', 'login', name = 'accounts.login'),
    url(r'^accounts/logout/$', 'logout', {"template_name": "registration/logged_out_DUlSine.html"}, name = 'accounts.logout'),
)

urlpatterns += patterns('DUlSine.views.DPS',
    url(r'^(?P<structure>\d+)/DPS/$', 'index', name = 'dps.index'),
    url(r'^(?P<structure>\d+)/DPS/(?P<dim_id>\d+)/$', 'details', name = 'dps.dimensionnement.details'),
    url(r'^(?P<structure>\d+)/DPS/(?P<dim_id>\d+)/inscription/(?P<wish_num>\d+)/$', 'inscription', name = 'dimensionnement.inscription'),

    # Creating a new DPS in  steps:
    # * information on the organizer and on the DPS
    #  * loop between 'modification' and 'verification'
    # * list of every days
    # * adding a new day
    # * looping between 'modification' and 'verification'
    url(r'^DPS/demande/$', 'demande', name = 'dps.demande'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/$', 'demande_details', name = 'dps.demande.details'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/envoyer/$', 'demande_envoyer', name = 'dps.demande.envoyer'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/verification/$', 'demande_verification', name = 'dps.demande.verification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/modification/$', 'demande_modification', name = 'dps.demande.modification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/$', 'dimensionnement', name = 'dps.demande.dimensionnement'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/verification/$', 'dimensionnement_verification', name = 'dps.demande.dimensionnement.verification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/modification/$', 'dimensionnement_modification', name = 'dps.demande.dimensionnement.modification'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/copy/$', 'dimensionnement_copy', name = 'dps.demande.dimensionnement.copy'),
    url(r'^DPS/demande/(?P<dps_hash>[0-9a-f]+)/dimensionnement/(?P<dim_id>\d+)/delete/$', 'dimensionnement_delete', name = 'dps.demande.dimensionnement.delete'),

    # Managing DPS
    url(r'^(?P<structure>\d+)/admin/DPS/$', 'admin_index', name = 'dps.admin.index'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/$', 'admin_details', name = 'dps.admin.details'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/dimensionnement/(?P<dim_id>\d+)/$', 'admin_dimensionnement', name = 'dps.admin.dimensionnement.details'),
    url(r'^(?P<structure>\d+)/admin/DPS/(?P<dps_id>\d+)/devis/$', 'devis', name = 'dps.admin.devis'),

    # Calendars in CalDav format
    # Two optional arguments given throug the url:
    # * avant : only return events that happend less than 'avant' days before
    # * apres : do not return events in more than 'apres' days
    url(r'^(?P<structure>\d+)/DPS/calendrier(?:/(?P<avant>\d+)(?:/(?P<apres>\d+))?)?/$', 'calendrier', name = 'dps.calendrier'),
)

urlpatterns += patterns('DUlSine.views.benevole',
    url(r'^(?P<structure>\d+)/benevoles/$', 'index', name = 'benevole.index'),
    url(r'^benevole/(?P<benevole_id>\d+)/$', 'details', name = 'benevole.details'),
    url(r'^benevole/(?P<benevole_id>\d+)/calendrier(?:/(?P<event_type>\w+))?(?:/(?P<avant>\d+)(?:/(?P<apres>\d+))?)?/$', 'calendrier', name = 'benevole.calendrier'),
    url(r'^benevole/inscription/$', 'inscription', name = 'benevole.inscription'),
    url(r'^benevole/inscription/confirmation/$', 'inscription_confirmation', name = 'benevole.inscription.confirmation'),
    url(r'^benevole/moncompte/$', 'moncompte', name = 'benevole.moncompte'),
)

DUlSine/models/DPS.py
# -*- coding: utf-8 -*-
# vim: set ts=4

import binascii
from decimal import Decimal
import math
import os

from django.db import models
from django.db.models import Q

from structure import Structure
from organisateur import Organisateur
from benevole import Benevole

from dulsine_commons import *


def random_hash():
    """ Create a random string of size 15 """
    return binascii.b2a_hex(os.urandom(15))


class DPS(models.Model):
    class Meta:
        app_label = 'DUlSine'
        verbose_name_plural = 'DPS'

    hash_id = models.CharField(unique = True, max_length = 30, default = random_hash)
    structure = models.ForeignKey(Structure, null = True, blank = True)

    organisateur = models.ForeignKey(Organisateur)
    intitule = models.CharField(max_length = 200)
    objet = models.CharField(max_length = 200)

    lieu = models.CharField(max_length = 400)
    circuit = models.CharField(max_length = 1, choices = CIRCUITS, default = CIRCUITS[0][0])
    superficie = models.IntegerField()
    distance = models.IntegerField()
    risques = models.CharField(max_length = 200)

    adresse_rdv = models.CharField(max_length = 500)
    contact_sur_place_nom = models.CharField(max_length = 200)
    contact_sur_place_prenom = models.CharField(max_length = 200)
    contact_sur_place_civilite = models.CharField(max_length = 4, choices = CIVILITES, default = CIVILITES[0][0])
    contact_sur_place_telephone = models.CharField(max_length = 20)

    prix = models.IntegerField(default = 0)
    remarques = models.CharField(max_length = 500, blank = True)

    def __unicode__(self):
        return self.intitule


RISQUES_P2 = (
    (Decimal("0.25"), 'Public Assis : spectacle, cérémonie culturelle, réunion publique'),
    (Decimal("0.3"), 'Public debout : cérémonie culturelle, réunion publique,restauration, exposition, foire, salon, comice agricole, ..'),
    (Decimal("0.35"), 'Public debout : spectacle avec public statique, fête foraine, rendez-vous sportif avec protection du public par rapport à l’évènement, ...'),
    (Decimal("0.4"), 'Public debout : spectacle avec public dynamique, danse, féria, fête votive, carnaval, spectacle de rue, évènement se déroulant sur plusieurs jours avec présence permanente du public')
)

RISQUES_E1 = (
    (Decimal("0.25"), 'Permanente (bâtiment, salle en dur,..) voies publics avec accès dégagés'),
    (Decimal("0.3"), 'Non permanente (gradins, tribunes, chapiteaux,..) espace naturels ≤ 2 hectares, brancardage 150m <longueur ≤300m Terrain en pente sur plus de 100 m'),
    (Decimal("0.35"), 'Espace naturels : 2 ha < surface ≤ 5 ha, brancardage 300m <longueur ≤600m, terrain en pente sur plus de 150m. Autres conditions d’accès difficile'),
    (Decimal("0.4"), 'Espaces naturels : surface > 5 hectares - Brancardage : longueur > 600m. Terrain en pente sur plus de 300m autres conditions d\'accès difficiles. Progression des secours rendue difficile par la présence du public')
)

RISQUES_E2 = (
    (Decimal("0.25"), '≤ 10 minutes'),
    (Decimal("0.3"), '> 10 minutes et ≤ 20 minutes'),
    (Decimal("0.35"), '> 20 minutes et ≤ 30 minutes'),
    (Decimal("0.4"), '> 30 minutes')
)


class Dimensionnement(models.Model):
    class Meta:
        app_label = 'DUlSine'
        ordering = ('debut', 'fin')

    DPS = models.ForeignKey(DPS)

    # If the name is not given, the DPS name is used instead
    nom = models.CharField(max_length = 200, blank = True)
    debut = models.DateTimeField()
    fin = models.DateTimeField()

    effectifs_acteurs = models.IntegerField(default = 0)
    age_acteurs = models.CharField(max_length = 50, blank = True)
    type_acteurs = models.CharField(max_length = 1, choices = TYPES_ACTEURS, blank = True)

    effectifs_public = models.IntegerField(default = 0)
    age_public = models.CharField(max_length = 50, blank = True)
    besoins_specifiques = models.CharField(max_length = 200, blank = True)

    medecin = models.CharField(max_length = 200, blank = True)
    infirmier = models.BooleanField(default = False)
    ambulance_prive = models.BooleanField(default = False)
    secours_public = models.CharField(max_length = 200, blank = True)
    secours_autre = models.CharField(max_length = 200, blank = True)

    centre_sdis = models.CharField(max_length = 200)
    hopital = models.CharField(max_length = 200)

    repas = models.BooleanField()

    P2 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_P2, default = RISQUES_P2[0][0])
    E1 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_E1, default = RISQUES_E1[0][0])
    E2 = models.DecimalField(max_digits = 3, decimal_places = 2, choices = RISQUES_E2, default = RISQUES_E2[0][0])
    IS = models.IntegerField(null = True, blank = True)

    def __unicode__(self):
        if self.nom is not None:
            return u"%s : %s" % (self.DPS, self.nom)
        else:
            return u"%s : %s - %s" % (self.DPS, self.debut, self.fin)

    def shortName(self):
        if self.nom is not None:
            return self.nom
        else:
            return u"%s - %s" % (self.debut, self.fin)

    def getIndice(self):
        """
         Compute the risque indicator according to the law
          @return the indicator
        """
        return self.P2 + self.E1 + self.E2

    def calculRISPublic(self):
        return self.calculRIS(True)

    def calculRISActeur(self):
        return self.calculRIS(False)

    def calculRIS(self, public):
        """
         Compute the RIS (number of first aiders) according to the given informations
          @param public: True if the DPS is targetting the public. False for the actors.
          @return the RIS
        """
        indice = self.P2 + self.E1 + self.E2
        P = 0
        if(public):
            P = self.effectifs_public
        else:
            P = self.effectifs_acteurs

        if(P > 100000):
            P = 100000 + (P - 100000) / 2

        return indice * P / 1000

    def calculISPublic(self):
        return self.calculIS(True)

    def calculISActeur(self):
        return self.calculIS(False)

    def calculIS(self, public):
        """
         Compute the minimal number of first aiders
          @param public: True if the DPS is targetting the public. False for the actors.
          @return the minimal number of first aiders
        """
        ris = self.calculRIS(public)
        if(ris <= 0.25):
            num_is = 0
        elif(ris <= 1.125):
            num_is = 2
            # A PAPS is not enough when protecting actors and if the public
            # helps took more than 30 minutes to come (E2 = 0.40)
            if(public is False or self.E2 == 0.40):
                num_is = 4
        elif(ris <= 4):
            num_is = 4
        else:
            num_is = math.ceil(ris)
            # Round to the nearest odd number (upper bound)
            if(num_is % 2 == 1):
                num_is += 1

        return num_is

    # Compute the required number of the given person
    def nombreISMax(self, formation):
        if(self.IS is None):
            return 0

        if(formation == DIPLOME_CI):
            return (self.IS - self.IS % 4) / 4
        elif(formation == DIPLOME_PSE2):
            return (self.IS - self.IS % 4) / 2 + (self.IS % 4) / 2
        elif(formation == DIPLOME_PSE1):
            return (self.IS - self.IS % 4) / 4 + (self.IS % 4) / 2
        elif(formation == DIPLOME_PSC1):
            return Team.objects.filter(dimensionnement = self, team_type = 1).count()
        else:
            assert(0)

    # Compute the current number of the given person
    def nombreIS(self, formation):
        return Inscription.objects.filter(team__dimensionnement = self, fonction = formation).count()

    # Compute the number of benevole marked as not available
    def nombreND(self):
        return Wish.objects.filter(dimensionnement = self, wish = WISH_ND).count()

    def nombreD(self):
        return Wish.objects.filter(dimensionnement = self).filter(~Q(wish = WISH_ND)).count()


from team import Team, Inscription, Wish

DUlSine/models/benevole.py
# -*- coding: utf-8 -*-
# vim: set ts=4

from django.contrib.auth.models import User
from django.db import models

from structure import Structure

from dulsine_commons import DIPLOME_CONDUCTEURS_LIST, DIPLOME_FORMATEURS_LIST, DIPLOME_SECOURS_LIST


class Benevole(models.Model):
    class Meta:
        app_label = 'DUlSine'
        ordering = ('user__last_name', 'user__first_name')

    def __unicode__(self):
        return u"%s (%s)" % (self.user.get_full_name(), self.structure.nom)

    user = models.OneToOneField(User)
    structure = models.ForeignKey(Structure, verbose_name='structure de ratachement')

    # TODO: use https://docs.djangoproject.com/en/dev/ref/contrib/localflavor/
    telephone = models.IntegerField('téléphone')
    adresse = models.CharField('adresse', max_length = 200)
    date_naissance = models.DateField('date de naissance')
    diplomes = models.CommaSeparatedIntegerField('diplômes', max_length = 200)

    def listDiplomes(self, lookup):
        diplomes = []
        for token in self.diplomes.split(','):
            token = int(token)
            if token in lookup:
                diplomes.append(lookup[token])
        return diplomes

    # Return the only diploma for 'Secours'
    def diplomesSecours(self):
        return self.listDiplomes(DIPLOME_SECOURS_LIST)

    # Return the list of diploma for 'Conducteurs'
    def diplomesConducteur(self):
        return self.listDiplomes(DIPLOME_CONDUCTEURS_LIST)

    # Return the list of diploma for 'Formateur'
    def diplomesFormateur(self):
        return self.listDiplomes(DIPLOME_FORMATEURS_LIST)

DUlSine/models/organisateur.py
# -*- coding: utf-8 -*-
# vim: set ts=4

from django.db import models

from dulsine_commons import CIVILITES


class Organisateur(models.Model):
    class Meta:
        app_label = 'DUlSine'

    nom = models.CharField(max_length = 200)
    adresse = models.CharField(max_length = 500)

    contact_nom = models.CharField(max_length = 200)
    contact_prenom = models.CharField(max_length = 200)
    contact_civilite = models.CharField(max_length = 4, choices = CIVILITES, default = CIVILITES[0][0])
    contact_fonction = models.CharField(max_length = 200)

    representant_nom = models.CharField(max_length = 200)
    representant_prenom = models.CharField(max_length = 200)
    representant_civilite = models.CharField(max_length = 4, choices = CIVILITES, default = CIVILITES[0][0])
    representant_fonction = models.CharField(max_length = 200)

    telephone = models.CharField(max_length = 20, blank = True)
    portable = models.CharField(max_length = 20, blank = True)
    fax = models.CharField(max_length = 20, blank = True)
    email = models.EmailField(max_length = 100)

    def __unicode__(self):
        return self.nom

    def contact(self):
        return u"%s %s %s" % (self.get_contact_civilite_display(), self.contact_nom, self.contact_prenom)

    def representantLegal(self):
        return u"%s %s %s" % (self.get_representant_civilite_display(), self.representant_nom, self.representant_prenom)

DUlSine/templates/dps/demande/dimensionnement_nouveau.html
{% extends 'auth.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% get_static_prefix %}dulsine/css/bootstrap-datetimepicker.min.css">
{% endblock %}

{% block titre %}DUlSine - Demande de DPS : Dimensionnement{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="{% url 'index' %}">Accueil</a> <span class="divider">/</span></li>
  <li><a href="{% url 'dps.demande' %}">Demande</a> <span class="divider">/</span></li>
  <li><a href="{% url 'dps.demande.details' dps.hash_id %}">{{ dps }}</a> <span class="divider">/</span></li>
  <li class="active">Dimensionnement</li>
</ul>
{% endblock %}

{% block corps %}
<div class="page-header">
  <h1>{% if nouveau %}Nouveau dimensionnement{% else %}Modification du dimensionnement{% endif %}</h1>
</div>

{% if form.errors %}
<div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Attention !</strong> certains éléments de la page sont mal remplis.
</div>
{% endif %}

<form action="" method="post" class="form-horizontal">
  {% csrf_token %}

  <h2>Information generales</h2>
  <div class="row">
    <div class="span6">
      <legend>Dimensionnement :</legend>
      <div class="control-group {% if form.nom.errors %}error{% endif %}">
        <label class="control-label" for="id_nom">Nom (facultatif)</label>
        <div class="controls">
          {{ form.nom }}
          {% for error in form.nom.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.debut.errors %}error{% endif %}">
        <label class="control-label" for="id_debut">Début</label>
        <div class="controls">
          <div id="debut" class="input-append">
            {{ form.debut }}
            <span class="add-on"><i class="icon-calendar"></i></span>
          </div>
          {% for error in form.debut.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.fin.errors %}error{% endif %}">
        <label class="control-label" for="id_fin">Fin</label>
        <div class="controls">
          <div id="fin" class="input-append">
            {{ form.fin }}
            <span class="add-on"><i class="icon-calendar"></i></span>
          </div>
          {% for error in form.fin.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span6">
      <legend>Public :</legend>
      <div class="control-group {% if form.effectifs_public.errors %}error{% endif %}">
        <label class="control-label" for="id_effectifs_public">Effectifs</label>
        <div class="controls">
          {{ form.effectifs_public }}
          {% for error in form.effectifs_public.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.age_public.errors %}error{% endif %}">
        <label class="control-label" for="id_age_public">Age</label>
        <div class="controls">
          {{ form.age_public }}
          {% for error in form.age_public.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.besoins_specifiques.errors %}error{% endif %}">
        <label class="control-label" for="id_besoins_specifiques">Besoins spécifiques</label>
        <div class="controls">
          {{ form.besoins_specifiques }}
          {% for error in form.besoins_specifiques.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="span6">
      <legend>Acteurs :</legend>
      <div class="control-group {% if form.effectifs_acteurs.errors %}error{% endif %}">
        <label class="control-label" for="id_effectifs_acteurs">Effectifs</label>
        <div class="controls">
          {{ form.effectifs_acteurs }}
          {% for error in form.effectifs_acteurs.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.age_acteurs.errors %}error{% endif %}">
        <label class="control-label" for="id_age_acteurs">Age</label>
        <div class="controls">
          {{ form.age_acteurs }}
          {% for error in form.age_acteurs.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.type_acteurs.errors %}error{% endif %}">
        <label class="control-label" for="id_type_acteurs">Type</label>
        <div class="controls">
          {{ form.type_acteurs }}
          {% for error in form.type_acteurs.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <legend>Risques</legend>
      <div class="control-group {% if form.P2.errors %}error{% endif %}">
        <label class="control-label" for="id_P2">Comportement du public</label>
        <div class="controls">
          {{ form.P2 }}
          {% for error in form.P2.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.E1.errors %}error{% endif %}">
        <label class="control-label" for="id_E1">Environnement</label>
        <div class="controls">
          {{ form.E1 }}
          {% for error in form.E1.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.E2.errors %}error{% endif %}">
        <label class="control-label" for="id_E2">Temps d'arrivée des secours public</label>
        <div class="controls">
          {{ form.E2 }}
          {% for error in form.E2.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <h2>Secours présents</h2>
  <div class="row">
    <div class="span6">
      <legend>Secours privés :</legend>
      <div class="control-group {% if form.medecin.errors %}error{% endif %}">
        <label class="control-label" for="id_medecin">Médecin</label>
        <div class="controls">
          {{ form.medecin }}
          {% for error in form.medecin.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.infirmier.errors %}error{% endif %}">
        <label class="control-label" for="id_infirmier">Infirmier</label>
        <div class="controls">
          {{ form.infirmier }}
          {% for error in form.infirmier.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.ambulance_prive.errors %}error{% endif %}">
        <label class="control-label" for="id_ambulance_prive">Ambulance Privée</label>
        <div class="controls">
          {{ form.ambulance_prive }}
          {% for error in form.ambulance_prive.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.secours_autre.errors %}error{% endif %}">
        <label class="control-label" for="id_secours_autres">Autres secours</label>
        <div class="controls">
          {{ form.secours_autre }}
          {% for error in form.secours_autre.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="span6">
      <legend>Secours publics :</legend>
      <div class="control-group {% if form.centre_sdis.errors %}error{% endif %}">
        <label class="control-label" for="id_centre_sdis">Centre de secours (Pompier)</label>
        <div class="controls">
          {{ form.centre_sdis }}
          {% for error in form.centre_sdis.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.hopital.errors %}error{% endif %}">
        <label class="control-label" for="id_hopital">Hopital</label>
        <div class="controls">
          {{ form.hopital }}
          {% for error in form.hopital.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="control-group {% if form.secours_public.errors %}error{% endif %}">
        <label class="control-label" for="id_secours_public">Présence de secours publics</label>
        <div class="controls">
          {{ form.secours_public }}
          {% for error in form.secours_public.errors %}
          <span class="help-inline">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <button type="submit" class="btn">{% if nouveau %}Ajouter le dimensionnement{% else %}Enregistrer{% endif %}</button>
</form>

{% endblock %}

{% block script %}
<script type="text/javascript" src="{% get_static_prefix %}dulsine/js/vendor/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}dulsine/js/vendor/bootstrap-datetimepicker.fr.js"></script>
<script type="text/javascript">
  $(function() {
    $('#debut, #fin').datetimepicker({
      format: 'dd/MM/yyyy hh:mm',
      pickSeconds: false,
      language: 'fr',
    });
  });
</script>
{% endblock %}

DUlSine/templates/dps/demande/dimensionnement_resume.html
{% extends 'auth.html' %}

{% block titre %}DUlSine - Résumé du DPS{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
  <li><a href="{% url 'index' %}">Accueil</a> <span class="divider">/</span></li>
  <li><a href="{% url 'dps.demande' %}">Demande</a> <span class="divider">/</span></li>
  <li><a href="{% url 'dps.demande.details' dps.hash_id %}">{{ dps }}</a> <span class="divider">/</span></li>
  <li class="active">Dimensionnement (verification)</li>
</ul>
{% endblock %}

{% block corps %}
<div class="page-header">
  <h1>Resume du dimensionnement</h1>
</div>

<div class="row">
  <div class="span12">
    <h4 class="modal-header">Dimensionnement</h4>
    <dl class="dl-horizontal">
      <dt>Intitulé</dt>
      <dd>{{ dim.nom }}
      <dt>Date</dt>
      {% if dim.debut|date:"d/m/y" == dim.fin|date:"d/m/y" %}
      <dd>Le {{ dim.debut|date:"l d/m/y" }} de {{ dim.debut|date:"H:i" }} à {{ dim.fin|date:"H:i" }}</dd>
      {% else %}
      <dd>Du {{ dim.debut|date:"l d/m/y" }} à {{ dim.debut|date:"H:i" }} au {{ dim.fin|date:"l d/m/y" }} à {{ dim.fin|date:"H:i" }}</dd>
      {% endif %}
      {% if dim.effectifs_public > 0 %}
      <dt>Public</dt>
      <dd>{{ dim.effectifs_public }} personnes de {{ dim.age_public }} (besoins specifiques : {{ dim.besoins_specifiques|default:"aucun" }})</dd>
      {% endif %}
      {% if dim.effectifs_acteurs > 0 %}
      <dt>Acteurs</dt>
      <dd>{{ dim.effectifs_acteurs }} personnes de {{ dim.age_acteurs }} ({{ dim.get_type_acteurs_display }})
      {% endif %}
    </dl>
  </div>

  <div class="span12">
    <h4 class="modal-header">Risques</h4>
    <dl class="dl-horizontal">
      <dt>Comportement</dt>
      <dd>{{ dim.get_P2_display }}</dd>
      <dt>Structure</dt>
      <dd>{{ dim.get_E1_display }}</dd>
      <dt>Secours public</dt>
      <dd>{{ dim.get_E2_display }}</dd>
    </dl>
  </div>

  <div class="span12">
    <h4 class="modal-header">Services de secours</h4>
    <dl class="dl-horizontal">
      <dt>Centre de secours</dt>
      <dd>{{ dim.centre_sdis }}</dd>
      <dt>Hopital</dt>
      <dd>{{ dim.hopital }}</dd>
      {% if dim.secours_public %}
      <dt>Secours public présent</dt>
      <dd>{{ dim.secours_public }}</dd>
      {% endif %}
      {% if dim.medecin %}
      <dt>Médecin</dt>
      <dd>{{ dim.medecin }}</dd>
      {% endif %}
      {% if dim.infirmier %}
      <dt>Présence d'un infirmier</dt>
      <dd>Oui</dd>
      {% endif %}
      {% if dim.ambulance_prive %}
      <dt>Ambulance privée</dt>
      <dd>Oui</dd>
      {% endif %}
    </dl>
  </div>
</div>

<center>
<a href="{% url 'dps.demande.dimensionnement.modification' dps.hash_id dim.id %}" class="btn btn-warning">Modifier</a>
<a href="{% url 'dps.demande.details' dps.hash_id %}" class="btn btn-success">Continuer</a>
</center>
{% endblock %}